# Site settings
title: OpenBudgets
description: > # this means to ignore newlines until "baseurl:"
  Upload, Visualize, Analyse public budget and spending data. Start exploring and learn stories behind budgets.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openbudgets.eu/" # the base hostname & protocol for your site

github_username:  openbudgets
github_repo: openbudgets.github.io
twitter_username: openbudgetseu
facebook_username: openbudgets

github_link: openbudgets

contact: anna.alberts@okfn.de

googleanalytics: UA-48682838-7

# Build settings
markdown: kramdown

permalink: pretty

paginate: 10
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate]
